
default: &default
  adapter: postgresql
  encoding: unicode
  database: examenback
  pool: 5
  username: examenb
  password: 123456789

development:
  adapter: postgresql
  encoding: unicode
  database: examenback
  pool: 5
  username: examenb
  password: 123456789


development:
  adapter: postgresql
  encoding: unicode
  database: examenback
  pool: 5
  username: examenb
  password: 123456789


production:
  adapter: postgresql
  encoding: unicode
  database: examenback
  pool: 5
  username: examenb
  password: 123456789
